#!/bin/bash     #for command based scripts

apt-get update
apt-get upgrade
apt-get install sudo -y

apt-get update && apt-get upgrade -y

dpkg-reconfigure tzdata

sudo adduser rvn
sudo usermod -aG sudo rvn
su - rvn
grep '^sudo' /etc/group   #check sudo x:27


sudo swapon --show
sudo fallocate -l 1G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
		/swapfile swap swap defaults 0 0  #/etc/fstab

swapon --show

cat /proc/sys/vm/swappiness
sudo sysctl vm.swappiness=25
  ^/etc/sysctl.conf 
  vm.swappiness=25
  
swapoff -v /swapfile  #to delete any pre-installed swap
sudo rm /swapfile  #to delete
 sudo ufw allow 777

wget https://github.com/RavenProject/Ravencoin/releases/download/v4.2.1/raven-4.2.1.0-x86_64-linux-gnu.tar.gz

https://github.com/RavenProject/Ravencoin/releases/download/v4.2.1/raven-4.2.1.0-x86_64-linux-gnu.tar.gz
tar -xzvf raven-4.2.1.0-x86_64-linux-gnu.tar.gz        #sudo?
 
rm -f raven-4.2.1.0-x86_64-linux-gnu.tar.gz

sudo cp ./raven-4.2.1.0/bin/* /usr/local/bin   


ravend &
raven-cli stop
cd ~/.raven
wget http://bootstrap.ravenland.org/blockchain.tar.gz
sudo mv ~/.raven/wallet.dat /usr/local/bin/  #move wallet
tar -xvzf blockchain.tar.gz
rm -r blockchain.tar.gz #deleting to save space


mv /usr/local/bin/wallet.dat ~/.raven/

/etc/ssh/sshd_config

sudo ufw allow 62222/tcp


sudo apt-get fail2ban
sudo cp /etc/fail2ban/fail2ban.conf /etc/fail2ban/fail2ban.local



sudo iptables -A INPUT -p tcp --dport 8767 -j ACCEPT 
sudo iptables -A INPUT -p udp --dport 8767 -j ACCEPT

addnode 95.179.180.160:8767

# raven-cli addnode 95.179.180.160:8767 add   

touch ~/.raven/raven.conf
nano ~/.raven/raven.conf 

# This is the 
#rpcpassword=SETYOURPASSWORDHERE #optional
#rpcallowip=IP_ADDRESS_OF_HOST_YOU_ACCESS_RAVEN-CLI_FROM #optional
upnp=1
listen=1
dbcache=1024
maxmempool=1492
disablewallet=1
logips=0
maxconnections=95
prune=42000
#maxuploadtarget=
whitelist=192.168.0.0/24
addnode=45.91.94.124
addnode=185.198.26.147
addnode=95.179.180.160
port=8767



